steps:
  ### Google Container Registry:
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', '${_IMAGE_}', '.']

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', '${_IMAGE_}']

  ### Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_AR_IMAGE_}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_IMAGE_}']

  - name: 'gcr.io/cloud-builders/kubectl'
    env:
    # - 'CLOUDSDK_COMPUTE_ZONE=''
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-5409'
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    args: ['apply', '-f', 'gke.yaml']

substitutions:
  _IMAGE_: 'gcr.io/cloud-computing-401614/container-2:latest'
  _AR_IMAGE_: 'us-central1-docker.pkg.dev/cloud-computing-401614/image-repository/container-2:latest'

# https://stackoverflow.com/questions/68779751/error-publishing-source-code-from-cloud-build-to-a-bucket-using-triggers
options:
  logging: CLOUD_LOGGING_ONLY

# Good Example reference: https://github.com/GoogleCloudPlatform/cloud-build-samples/blob/main/python-example-flask/cloudbuild.yaml